%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\SANJEEV BASHYAL\Documents\Project074\coordinates refined 43 points.csv
%
% Auto-generated by MATLAB on 29-Nov-2021 08:55:22

filename="C:\Users\SANJEEV BASHYAL\Documents\Project074\coordinates refined 43 points check 6-7.csv";
%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 29);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["X", "Y", "Z", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29"];
opts.SelectedVariableNames = ["X", "Y", "Z"];
opts.VariableTypes = ["double", "double", "double", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable(filename, opts);

%% Convert to output type
X = tbl.X;
Y = tbl.Y;
Z = tbl.Z;

%% Clear temporary variables
clear opts tbl